### ISSUE TITLE
공통 기능 Header 및 Footer 구현

### ISSUE THREAD

**Issue by mirang1024** [Dev-FE-1/team2-intranet-project-#10]
### Tasks
- [x] HTML로 마크업과 구조 정의
- [x] CSS로 스타일 정의
- [x] JS로 동작 정의
- [x] 컴포넌트 만들기

담당: 최미랑
