### ISSUE TITLE
발표 자료 만들기

### ISSUE THREAD

**Issue by mirang1024** [Dev-FE-1/team2-intranet-project-#114]
### Tasks
- [ ] 발표 자료는 PPT로 만들기
- [ ] PDF로 변환해서 공유하기
- [ ] 배포/가상환경에서의 시연연상 만들기 
*발표 자료 제출은 각 팀 팀장이 제출
*최종 결과물 제출: 전원 제출 ( 7회차 퀴즈 위치에 제출- 7/12 안내 예정 )
