### ISSUE TITLE
프로필사진 컴포넌트 구현

### ISSUE THREAD

**Issue by clara-shin** [Dev-FE-1/team2-intranet-project-#12]
### Tasks
- [x] 프로필사진 UI 개발: 사진 사이즈 상관없이 정중앙 배치 및 원형 이미지 구현
- [x] 사진 불러오기 및 등록 기능
- [x] 사진 삭제 기능 및 이미지 초기화 구현

담당: 신혜진

**Comment by clara-shin** [comment]
헤더에 링크를 붙여 테스트 중
여전히 새로고침 되면 에러는 없으니 css가 뻥나는 현상 발생
