### ISSUE TITLE
임직원 정보등록, 수정 컴포넌트 구현

### ISSUE THREAD

**Issue by sbs1253** [Dev-FE-1/team2-intranet-project-#14]
### Tasks
- [x] #16
- [x] js 기능 추가해서 동적 기능 구현
- [x] 사용자 정보 파일 생성 후 동작 확인

담당: 송병훈

**Comment by sbs1253** [comment]
- [ ] 사용자 정보 서버통신해서 받아오는 기능 구현 = 현재 더미파일에서 불러오기중 
- [ ] 코드 리팩토링
   - [ ] 리스트를 사용자 정보를 통해 생성하는 컴포넌트 구현
   - [ ] 현재 만든 함수가 의존성이 높아서 함수 분리
