### ISSUE TITLE
반응형 디자인, 이미지 처리(이머거)

### ISSUE THREAD

**Issue by clara-shin** [Dev-FE-1/team2-intranet-project-#140]
### Tasks
- [x] 로그인페이지 이미지 처리
- [x] 근태신청 페이지 반응형디자인 재조정
- [ ] 근태신청카드 보여지도록 아코디언
