### ISSUE TITLE
공통 모달 컴포넌트

### ISSUE THREAD

**Issue by sbs1253** [Dev-FE-1/team2-intranet-project-#20]
### Tasks
- [x] 모달 컴포넌트 구현
  - [x] 삭제, 근무시작, 근무종료 별 텍스트 출력

- 이렇게 사용하면 됩니다. 
const modal = new Modal('근무시작');
this.el.append(modal.el);

담당: 송병훈

**Comment by sbs1253** [comment]
- [ ] 모달창에서 삭제, 근무시작, 근무종료 버튼 클릭 시 동작 구현
