### ISSUE TITLE
[리팩토링] 프로필이미지 컴포넌트 함수분리

### ISSUE THREAD

**Issue by clara-shin** [Dev-FE-1/team2-intranet-project-#208]
### Tasks
- [x] 이미지 처리함수(readPhoto, scaleCanvas, optimizePhoto)
- [x] Cloudinary 업로드 관련 함수
- [x] 이벤트핸들러만 모아둔 함수(setAddEventListener, processReduce, removePhoto)
- [x] 이미지를 가져와서 업데이트하는 함수(fetchProfileImage, updateProfileImage)
- [x] 이미지 프로파일 클래스
