### ISSUE TITLE
[리팩토링] 갤러리 컴포넌트 클래스 분리

### ISSUE THREAD

**Issue by mirang1024** [Dev-FE-1/team2-intranet-project-#210]
### Tasks
- [x] 공통 기능을 추출해 Gallery 클래스 생성 후 AdminGallery와 Employee 갤러리가 이를 상속하도록 분리
- [x] Gallery 클래스의 메서드 분류 작업
- [x] 향후 확장성을 고려하여 모달 컴포넌트 생성
