### ISSUE TITLE
[리팩토링] UserInfo 클래스 함수분리

### ISSUE THREAD

**Issue by clara-shin** [Dev-FE-1/team2-intranet-project-#213]
### Tasks
- [ ] constants (클래스내부 상수)
- [ ] dataLoaders (데이터 로딩)
- [ ] dataManagement (데이터 관리)
- [ ] eventHandlers (이벤트 핸들러)
- [ ] uiHelpers (UI 관련된 헬퍼 함수)
- [ ] validatorHelpers (유효성 검사와 관련된 함수 및 이벤트 핸들러)
- [ ] UserInfo 클래스

### Help the Problem
브랜치 확인을 안하고 머지해서 #209 에 commit이 포함되어 있음
[commit 21772ad](https://github.com/Dev-FE-1/team2-intranet-project-/pull/209) 링크에 있음
