### ISSUE TITLE
백엔드 데이터베이스 구축, 직원 CRUD API 구현

### ISSUE THREAD

**Issue by nakyeonko3** [Dev-FE-1/team2-intranet-project-#24]
### Tasks
- [ ] API 문서 작성
- [ ] sql 문을 통해 DB 초기화 기능
- [ ] 직원 삭제
- [ ] 직원 추가
- [x] 직원 리스트 가져오기
- [ ] 직원 데이터 수정
- [ ] 회원가입(암호화X, 로그인 대조만 가능)

### 예상 기간
토요일 23시 59분까지 완료 예정

**Comment by nakyeonko3** [comment]
인메모리 데이터 베이스 구현완료
```js
import sqlite3 from 'sqlite3';

class ConnectionMaker {
  constructor() {}

  makeConnection() {
    const db = new sqlite3.Database(`:memory:`, (err) => {
      if (err) {
        console.error('Error connecting to database:', err);
      } else {
        console.log('Connected to the in-memory SQlite database.');
      }
    });

    return db;
  }
}

export default class InMemoDatabase {
  constructor() {
    this.db = new ConnectionMaker().makeConnection();
    this.createTable();
  }

  createTable() {
    this.db.serialize(() => {
      this.db.run(`
        CREATE TABLE IF NOT EXISTS Employees (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          email TEXT,
          phone TEXT,
          position TEXT,
          profileImg TEXT,
          password TEXT
        )`);
    });
  }

  insertEmployees(employees) {
    (employees || []).forEach((employee) => {
      this.insertEmployee(employee);
    });
  }

  insertEmployee({ name, email, phone, position, profileImg }) {
    const sql = `INSERT INTO Employees (name, email, phone, position,  profileImg) VALUES (?, ?, ?, ?, ?)`;
    this.db.run(sql, [name, email, phone, position, profileImg], (err) => {
      if (err) {
        console.error('Error inserting Employee:', err);
      }
    });
  }

  getAllEmployees(callback) {
    const sql = 'SELECT * FROM Employees';
    this.db.all(sql, [], (err, rows) => {
      if (err) {
        console.error('Error selecting all Employees:', err);
      }
      callback(rows);
    });
  }
}

```
