### ISSUE TITLE
직원 근태 신청 리스트 프리뷰 페이지 

### ISSUE THREAD

**Issue by nakyeonko3** [Dev-FE-1/team2-intranet-project-#25]
### Tasks
- [x] 마크업 작업, 스타일시트 작업
- [x] js 컴포넌트로 변경하기
- [x] 백엔드와 연동하기, 직원 근태 리스트 가져오기

**Comment by nakyeonko3** [comment]
![image](https://github.com/Dev-FE-1/team2-intranet-project-/assets/59277499/2e28d645-32b4-402e-a0cc-cdbd10a88b01)

**Comment by nakyeonko3** [comment]
마크업 작업, 스타일시트 작업 완료
 js 컴포넌트로 전환 작업중
![image](https://github.com/Dev-FE-1/team2-intranet-project-/assets/59277499/51bbbefe-0718-4030-9843-a0841a9ab3e7)

**Comment by nakyeonko3** [comment]
리스트 사이선 추가
![image](https://github.com/Dev-FE-1/team2-intranet-project-/assets/59277499/c373714f-841c-49b1-b4d8-8d166276264a)

**Comment by nakyeonko3** [comment]
js 컴포넌트로 변경 완료
```js
import './AttendanceList.css';

export default class AttendanceList {
  constructor() {
    this.elem = document.createElement('section');
    this.render();

    this.attendanceType = {
      연차: '-attendance-annual-leave',
      반차: '-attendance-half-day',
      조퇴: '-attendance-early-out',
      기타: '-attendance-etc',
    };

    const attendanceListItems = [
      {
        name: '젠슨황',
        type: '조퇴',
        content: '조퇴 하겠습니다.',
        profileImg: 'https://i.imgur.com/4RPlpYo.png',
      },
      {
        type: '연차',
        content: '연차를 쓰겠습니다.',
        profileImg: 'https://i.imgur.com/4RPlpYo.png',
      },
      {
        name: '젠슨황',
        type: '기타',
        content: '기타 사유',
        profileImg: 'https://i.imgur.com/4RPlpYo.png',
      },
      {
        name: '젠슨황',
        type: '반차',
        content: '반차를 쓰겠습니다.',
        profileImg: 'https://i.imgur.com/4RPlpYo.png',
      },
      {
        name: '젠슨황',
        type: '조퇴',
        content: ' 질병 조퇴 요청합니다.',
      },
    ].slice(-4);

    this.render({ attendanceListItems });
  }

  attendanceItemTamplate({
    name = '이름 없음',
    type = '기타',
    content = '',
    profileImg = 'https://i.imgur.com/JJEqrWE.png',
  }) {
    return /*html*/ `
    <li class="attendance-item">
    <img src="${profileImg}" alt="profile image" srcset="" />
    <div class="l-attendance-item">
      <div class="attendance-item__status">
        <h2 class="${this.attendanceType[type]}">${type}</h2>
        <p>${content}</p>
      </div>
      <div class="attendance-item__name">
        <p>${name}</p>
      </div>
    </div>
  </li>
    `;
  }

  renderAttendanceItems(attendanceListItems) {
    return attendanceListItems
      .map((attendanceItem) => this.attendanceItemTamplate(attendanceItem))
      .join(' ');
  }

  render(state) {
    this.elem.innerHTML = /*html*/ `
    <section class="attendance-list">
    <header class="attendance-list__header">
      <h1>Attendance State</h1>
      <button>근태현황 바로가기</button>
    </header>
    <ul class="attendance-items">
      ${state ? this.renderAttendanceItems(state.attendanceListItems) || '' : ''}
    </ul>
  </section>
    `;
  }
}


```

**Comment by nakyeonko3** [comment]
백엔드 데이터 연동 완료
```js
import axios from 'axios';
import './AttendanceList.css';

export default class AttendanceList {
  constructor() {
    this.elem = document.createElement('section');
    this.render();
    this.defaultProfileImg = 'https://i.imgur.com/JJEqrWE.png';

    this.attendanceType = {
      연차: '-attendance-annual-leave',
      반차: '-attendance-half-day',
      조퇴: '-attendance-early-out',
      기타: '-attendance-etc',
    };
    this.updateAttendances();
  }

  async getAttendances() {
    try {
      const response = await axios.get('http://localhost:8080/api/attendances');
      return response.data.data;
    } catch (error) {
      console.error('attendances근태 리스트 데이터를 가져오는 중에 에러 발생', error);
      return [];
    }
  }

  async updateAttendances() {
    const attendances = await this.getAttendances();
    this.render({ attendances });
  }

  attendancesListItemTamplate({ name, type, content, profileImg }) {
    return /* HTML */ `
      <li class="attendance-item">
        <img src="${profileImg || this.defaultProfileImg}" alt="profile image" srcset="" />
        <div class="l-attendance-item">
          <div class="attendance-item__status">
            <h2 class="${this.attendanceType[type] || ''}">${type}</h2>
            <p>${content || '신청합니다.'}</p>
          </div>
          <div class="attendance-item__name">
            <p>${name || ''}</p>
          </div>
        </div>
      </li>
    `;
  }

  attendanceItems(attendances) {
    return (attendances || [])
      .slice(-4)
      .map((attendance) => this.attendancesListItemTamplate(attendance))
      .join(' ');
  }

  render(state) {
    this.elem.innerHTML = /* HTML */ `
      <section class="attendance-list">
        <header class="attendance-list__header">
          <h1>Attendance State</h1>
          <button>근태현황 바로가기</button>
        </header>
        <ul class="attendance-items">
          ${state ? this.attendanceItems(state.attendances) || '' : ''}
        </ul>
      </section>
    `;
  }
}

```
