### ISSUE TITLE
갤러리 컴포넌트 구현

### ISSUE THREAD

**Issue by mirang1024** [Dev-FE-1/team2-intranet-project-#27]
### Tasks
- [x]  HTML로 마크업과 구조 정의
- [x]  CSS로 스타일 정의
- [ ]  JS로 동작 정의
- [ ]  컴포넌트 만들기
