### ISSUE TITLE
직원 마이페이지 구현

### ISSUE THREAD

**Issue by sbs1253** [Dev-FE-1/team2-intranet-project-#28]
### Tasks
- [x] 마이페이지 html, css로 구현
- [x] js클래스로 컴포넌트 구현
- [x] js 동적 기능 추가
- [ ] 코드 리팩토링
  - [ ] 함수분리
  - [ ] 변수, 함수, 클래스명 컨벤션에 맞게 변경

담당: 송병훈
