### ISSUE TITLE
README.md에 역할 분담 및 팀원 역량 추가

### ISSUE THREAD

**Issue by mirang1024** [Dev-FE-1/team2-intranet-project-#32]
### Tasks
- [x] 팀원 역량 취합
- [x] 팀원 역량 정리 후 추가
- [x] 역할 분담 추가
