### ISSUE TITLE
파일구조 정리 및 폴더이름 변경

### ISSUE THREAD

**Issue by clara-shin** [Dev-FE-1/team2-intranet-project-#36]
### Tasks
- [x] /src/components로 이름변경
- [x] /src/css/ 삭제
- [x] /src/pages 밑에 각자 이름으로 만든 폴더에 먼저 작업 후, 통합 예정
