### ISSUE TITLE
라우팅 함수 추가하기, 코드 합치기

### ISSUE THREAD

**Issue by nakyeonko3** [Dev-FE-1/team2-intranet-project-#44]
김민태 강사님 코드를 바탕으로 라우팅 함수 구축하기
### Tasks
- [x] 라우팅 함수 만들고 커밋하기
- [ ] 라우팅 함수에 홈 화면 페이지와 연결하기
- [ ] 라우팅 함수에 로그인 화면 페이지와 연결하기
