### ISSUE TITLE
향후 해야하는 일들

### ISSUE THREAD

**Issue by mirang1024** [Dev-FE-1/team2-intranet-project-#58]
# Tasks

## 회의에 논의된 Tasks
- [x] 라우팅을 전체 다 해보고 데이터 잘 불러와지는지 확인
- [x] 로그인 엔트리포인트 정하기
- [x] 근태 신청 조회 페이지 > 낙연님 오시면 진행
- [x] 미디어쿼리
- [ ] 페이지 디자인
- [ ] 유저플로우 이미지 = 페이지 경험 순서도
- [x] sqllite3 쿼리문으로 하는 작업
- [x] 관리자는 유저 데이터랑 갤러리 전체 데이터 불러오기 
- [x] 직원은 해당 유저의 데이터 갤러리, 근태 데이터

## (추가) 프로젝트 관리 및 일정 부분
- [ ] 프로젝트 마감일자 정하기( 7월 12일 마감이지만 실제 마감일 전에 프로젝트를 마감하는편이 나음)
- [ ] 각자 페이지별 기능 정의 하기

### 프로필 이미지 등록, 갤러리 이미지 등록 
- [x] 이미지 저장 방식 정하기
- [x] 이미지 전송, 백엔드 프론트엔드 간의 이미지 전송 로직 구현하기

### 사용자 로그인 페이지
- [x] 사용자 로그인 기능 구현: 로그인 유효성 로직 구현
- [ ] 사용자 로그인 기능 구현: 사용자 로그인 성공과 실패 구현
- [ ] 사용자 로그인 기능 구현: 로그인 성공 이후 사용자 정보 session storage나 localstorage에 저장하게 하기 또는 props로 다른 컴포넌트로 사용자 정보 전달하기

### 직원관리페이지(직원 리스트 페이지), 직원 수정 및 추가 페이지

- [x] 직원 관리 페이지와 직원 등록수정 페이지와 사용자 정보(이미지, 이름, 비밀번호) 전달 로직 구현(완료)
- [ ] 직원 삭제 기능(모달, 전체 삭제 기능)
- [ ] 직원 등록 기능
- [ ] 직원 정보 수정 기능

### 근태 신청 및 조회 페이지
- [ ] 근태 신청 기능
- [x] 근태 조회 기능
- [ ] 근태 수정 기능(삭제 불가, 근태 사유 종류 수정 불가, 근태 사유 내용만 수정 가능)

## 근무시간, 근무 상태 페이지
- [ ] 근무 시간 갱신 기능
- [ ] 근무 상태(근무전, 근무후, 근무 종료) 중에 하나로  변경 기능

### 직원 개인정보 수정
- [ ] 직원 개인정보(비밀번호, 프로필이미지, 등) 변경 기능

### 직원 마이페이지
- [ ] 로그인된 해당 직원의 개인정보를 확인하는 기능
- [ ] 근무 상태 확인 기능

### Header
- [x] 사용자 타입별로 글로벌네비게이션바(gnb)를 함수로 분리하기
- [x] 로그아웃 버튼에 대한 이벤트 리스너 추가
- [x] 메뉴 아이콘 부분 수정하기

### Footer
- [x] 깃허브 리포지토리로 이동 시 새탭 이동/기존탭에서 이동 방식 결정 후 반영하기

### 갤러리 라우팅 및 CSS 수정
- [x] axios를 사용해 데이터 가져오는 방식으로 변경하기
- [x] 데이터 가져와지는지 및 화면 정상 조회되는지 확인하기
- [x] 이미지 데이터 imgur에서 로컬 이미지로 바꾸기  
- [x] 가로 스크롤 지우기
### 선택 기능 추가(시간이 된다면)
- [ ] 레이지로딩 구현
- [ ] AdminGallery에서 카드 생성, 삭제, 편집 가능하도록 추가(CUD) > 모달창을 통해?
