### ISSUE TITLE
사원 리스트 테이블 구현

### ISSUE THREAD

**Issue by nakyeonko3** [Dev-FE-1/team2-intranet-project-#9]
### Tasks
 - [x] 직원 검색 기능
 - [ ] 직원 삭제 기능
 - [ ] 직원 여러명 삭제 기능
 - [ ] 직원 등록 기능

**Comment by nakyeonko3** [comment]
html css로 간단하게 구현하기
![image](https://github.com/Dev-FE-1/team2-intranet-project-/assets/59277499/6ada960f-57de-4312-8efe-960f96c92be9)

**Comment by nakyeonko3** [comment]
## Help the Problem
 - [ ] 사이트가 테이블 헤더 부분(버튼이 있는 부분) 위치가 화면 양 끝으로 이동함. 이 문제 해결중

**Comment by nakyeonko3** [comment]
해결완료
![image](https://github.com/Dev-FE-1/team2-intranet-project-/assets/59277499/083e3afc-562c-48ab-949b-0e76002b9a6a)

**Comment by nakyeonko3** [comment]
[![image](https://github.com/Dev-FE-1/team2-intranet-project-/assets/59277499/da76a7f5-200b-4248-83b6-816fd872cf3b)](https://i.imgur.com/XFKXy93.png)

**Comment by nakyeonko3** [comment]
![image](https://github.com/Dev-FE-1/team2-intranet-project-/assets/59277499/6dc426cb-36a9-41bb-92a7-0448f6e7ee69)
